---
configs:
    use: 'two_ten'
    two_eight:
        ansible_version: '2.8.20'
        vagrant_box: 'generic/rocky8'
    two_nine:
        ansible_version: '2.9.27'
        vagrant_box: 'generic/rocky8'
    two_ten:
        ansible_version: '2.10.7'
        vagrant_box: 'generic/rocky8'
