---
configs:
    use: 'two_ten'
    two_eight:
        ansible_version: '2.8.17'
        vagrant_box: 'geerlingguy/centos8'
    two_nine:
        ansible_version: '2.9.15'
        vagrant_box: 'geerlingguy/centos8'
    two_ten:
        ansible_version: '2.10.3'
        vagrant_box: 'geerlingguy/centos8'
