---
configs:
    use: '3.x'
    2.8:
        ansible_version: '2.8.20'
        vagrant_box: 'generic/rocky8'
    2.9:
        ansible_version: '2.9.27'
        vagrant_box: 'generic/rocky8'
    2.10:
        ansible_version: '2.10.7'
        vagrant_box: 'generic/rocky8'
    3.x:
        ansible_version: '3.4.0'
        vagrant_box: 'generic/rocky8'
    4.x:
        ansible_version: '4.8.0'
        vagrant_box: 'generic/rocky8'
