---
configs:
    use: 'two_ten'
    two_eight:
        vagrant_box: 'geerlingguy/centos8'
        ansible_version: '2.8.20'
    two_nine:
        vagrant_box: 'geerlingguy/centos8'
        ansible_version: '2.9.27'
    two_ten:
        vagrant_box: 'geerlingguy/centos8'
        ansible_version: '2.10.7'
